exclude_paths:
    - "components/"
engines:
    duplication:
        enabled: true
        config:
            languages:
                - javascript
        exclude_fingerprints:
            - d72870d89bbaccb7e404a637ac3e9a04
            - 0b99cc6e5e209627d1aac8b3c639dd19

eslint:
    enabled: true
    config:
        extensions:
            - .es6
            - .js

ratings:
    paths:
        - "**.es6"
        - "**.js"
